# Generated by Django 4.1.4 on 2022-12-31 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('grade', models.IntegerField()),
                ('division', models.CharField(max_length=10)),
                ('roll_no', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('bus_stop', models.CharField(max_length=100)),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes_app.routesmodel')),
            ],
        ),
    ]
