# Generated by Django 4.1.4 on 2022-12-31 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes_app', '0002_alter_routesmodel_bus_id_alter_routesmodel_driver_id'),
        ('student_app', '0002_alter_studentmodel_route_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentModel',
            new_name='Student',
        ),
    ]
